default:
  golem_name: CSIemail
  golem_version: 0.0.3
  app_prod: no
  smtp_creds: mail_improvast
  sender: lefkiospaik@gmail.com
  db_path: DB/csi_db.db
  db_users: DB/credentials.sqlite
  users_passphrase: acsrocks
  acs_template: data-raw/ACS CSI template.xlsx
  th_template: data-raw/TH CSI template.xlsx
production:
  app_prod: yes
  sender: accounts@acscyprus.com
  smtp_creds: acs
dev:
  app_prod: no
  golem_wd: !expr here::here()
  sender: lefkiospaik@gmail.com
  smtp_creds: mail_improvast
